default:
  adapter: mysql2
  database: cats
  username: dfeldbaum
  password: rebecca88
  host: localhost
development:
  adapter: mysql2
  database: cats
  username: dfeldbaum
  password: rebecca88
  host: localhost
production:
  adapter: mysql2
  database: cats
  username: dfeldbaum
  password: rebecca88
  host: localhost